name: cd

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  cd:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.14.0]
    env:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.14.0'
          cache: yarn

      - name: Install dependencies
        run: yarn install

      # - name: Lint JS
      #   run: yarn lint:js

      # - name: Lint Style
      #   run: yarn lint:style

      - name: Generate
        run: yarn generate

      - name: Netlify Draft Deploy
        if: github.ref != 'refs/heads/master'
        run: npx netlify-cli deploy --dir=./dist

      - name: Netlify Production Deploy
        if: github.ref == 'refs/heads/master'
        run: npx netlify-cli deploy --prod --dir=./dist


