name: cd

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  cd:
    runs-on: ubuntu-latest
    env:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: pnpm/action-setup@v3.0.0
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version-file: '.tool-versions'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --ignore-scripts

      - name: Prisma generate types and etc
        run: pnpm prisma generate

      - name: Nuxi prepare
        run: pnpm prepare

      - name: Lint JS
        run: pnpm lint:js

      - name: Lint Style
        run: pnpm lint:style

      - name: Type check
        run: pnpm typeCheck

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Netlify Draft Deploy
        if: github.ref != 'refs/heads/main'
        run: netlify deploy --build --alias $SHORT_SHA

      - name: Netlify Production Deploy
        if: github.ref == 'refs/heads/main'
        run: netlify deploy --build --prod --alias production
